name: .NET Core

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.200

    - name: Install dependencies
      run: dotnet restore ./src/Codeizi

    - name: Build
      run: dotnet build ./src/Codeizi --configuration Release --no-restore

    - name: Test
      run: dotnet test ./src/Codeizi --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        file: ./tests/**/coverage.opencover.xml
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: Codeizi-Tools/codeizi-cli        
        fail_ci_if_error: true